# Generated by Django 5.1.7 on 2025-03-27 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('carrier', models.CharField(max_length=255)),
                ('office_address', models.TextField()),
                ('home_terminal', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_hours_today', models.FloatField(default=0)),
                ('total_hours_past_7_days', models.FloatField(default=0)),
                ('available_hours_tomorrow', models.FloatField(default=0)),
                ('consecutive_hours_off', models.FloatField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty', 'On Duty (not driving)')], max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_number', models.CharField(max_length=100, unique=True)),
                ('shipment_details', models.TextField()),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.logentry')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=50, unique=True)),
                ('state', models.CharField(max_length=50)),
                ('total_miles_driven', models.FloatField(default=0)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.driver')),
            ],
        ),
        migrations.AddField(
            model_name='logentry',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicle'),
        ),
    ]
