# Generated by Django 5.1.7 on 2025-03-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='license_plate',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
