# Generated by Django 5.1.7 on 2025-03-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingdocument',
            old_name='shipment_details',
            new_name='shipper_commodity',
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='available_hours_next_day',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='reset_34_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='total_hours_past_5_days',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='total_hours_past_8_days',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='logentry',
            name='home_terminal_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='total_mileage_today',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='logentry',
            name='total_miles_driving_today',
            field=models.FloatField(default=0),
        ),
    ]
