# Generated by Django 5.1.7 on 2025-04-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_driver_email_alter_trip_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('total_hours', models.FloatField(default=0.0)),
                ('stops', models.IntegerField(default=0)),
                ('rest_hours', models.FloatField(default=0.0)),
                ('fueling_count', models.IntegerField(default=0)),
                ('distance_covered', models.FloatField(default=0.0)),
                ('pickup_time', models.FloatField(default=0.0)),
                ('dropoff_time', models.FloatField(default=0.0)),
            ],
        ),
    ]
