# Generated by Django 5.1.7 on 2025-04-05 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_truck_assigned_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='assigned_truck',
        ),
        migrations.AlterField(
            model_name='truck',
            name='assigned_driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_truck', to=settings.AUTH_USER_MODEL),
        ),
    ]
