# Generated by Django 5.1.7 on 2025-04-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_driverlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverlog',
            old_name='date',
            new_name='log_date',
        ),
        migrations.AlterField(
            model_name='driverlog',
            name='dropoff_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverlog',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
