# Generated by Django 5.1.7 on 2025-04-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_date_driverlog_log_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverlog',
            old_name='total_hours',
            new_name='hours_worked',
        ),
    ]
