# Generated by Django 5.1.7 on 2025-04-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_total_hours_driverlog_hours_worked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverlog',
            old_name='fueling_count',
            new_name='fuel_stop_locations',
        ),
    ]
