# Generated by Django 5.1.7 on 2025-04-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_fueling_count_driverlog_fuel_stop_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlog',
            name='fueling_count',
            field=models.IntegerField(default=0),
        ),
    ]
