# Generated by Django 5.1.7 on 2025-04-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_driverlog_fueling_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlog',
            name='fuel_stop_locations',
            field=models.FloatField(default=0.0),
        ),
    ]
