# Generated by Django 5.1.7 on 2025-04-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_driverlog_fuel_stop_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlog',
            name='fuel_stop_locations',
            field=models.JSONField(default=list),
        ),
    ]
