# Generated by Django 5.1.7 on 2025-04-01 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_driverlog_fuel_stop_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlog',
            name='driver_id',
        ),
        migrations.AddField(
            model_name='driverlog',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.driver'),
            preserve_default=False,
        ),
    ]
