# Generated by Django 5.1.7 on 2025-04-01 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_driverlog_driver_id_driverlog_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlog',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.driver'),
        ),
    ]
